apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp  # <---"find Pods with this label"
  template:
    metadata:
      labels:
        app: myapp # <---"give all my Pods this label"
    spec:
      containers:
        - name: myapp
          image: maalchand/myapp:latest
          ports:
            - containerPort: 8080