
name: My App Pipeline

on:
  push:
    branches:
      - main
      - branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies  
        run:  pip install pytest
        
      - name: Run tests
        run: pytest test_app.py


  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t maalchand/myapp:{{ github.sha }} .

      - name: Push Docker image
        run: docker push maalchand/myapp:{{ github.sha }}  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy confirmation
        run: echo "Deploying to production"      